baseURL: 'https://cookiehoodie.github.io/blog'
languageCode: en-us
title: CH's Blog
theme: papermod
googleAnalytics: G-LGTT6WLGH5
params:
  env: production
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  comments: true
  label:
    text: "CH's Blog"
    icon: avatar.png
  homeInfoParams:
    Title: Welcome to my blog!👋
    Content: Hope you find something useful here 🎉
  socialIcons: 
    - name: "github"
      url: "https://github.com/CookieHoodie"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/chin-hang-ong/"
markup:
  highlight:
    lineNos: true
outputs:
  home:
    - HTML
    - RSS
    - JSON 
menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 1
    - identifier: search
      name: Search
      url: /search/
      weight: 2
    - identifier: portfolio
      name: Portfolio
      url: https://cookiehoodie.github.io/
      weight: 3